spring:
  application:
    name: api
  
  mvc:
    view:
      prefix: /
      suffix: .html
  
  web:
    resources:
      static-locations: classpath:/static/,classpath:/templates/
  
  # Database Configuration (PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5432/cogirihub
    driver-class-name: org.postgresql.Driver
    username: cogirihub
    password: 12341234
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---

